### ISSUE TITLE
Examples Six/Seven segfault

### ISSUE THREAD

**Issue by cbm755** [connortannahill/bacoli_py#2]
I've tested ExampleOne.py up to ExampleFive: those seem to work.

```
python3 ExampleSix.py 
Segmentation fault (core dumped)
```

Haven't investigated further yet.  I'm on Fedora 31.  bacoli-py installed with `pip3 install --user bacoli-py`.

**Comment by cbm755** [comment]
I learned [how to gdb python](https://stackoverflow.com/a/2664232)

```
$ gdb python3
GNU gdb (GDB) Fedora 8.3-6.fc30

----- 8< ------

(gdb) run ExampleSix.py 
Starting program: /usr/bin/python3 ExampleSix.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe7c49700 (LWP 20280)]
[New Thread 0x7fffe7448700 (LWP 20281)]
[New Thread 0x7fffe2c47700 (LWP 20282)]
[New Thread 0x7fffe2446700 (LWP 20283)]
[New Thread 0x7fffddc45700 (LWP 20284)]
[New Thread 0x7fffdb444700 (LWP 20285)]
[New Thread 0x7fffd8c43700 (LWP 20286)]

Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007fffd57c4f3a in iniyp (t0=0.80273935294366627, npde=<optimized out>, 
    kcol=4, nint=25, neq=102, ncpts=102, xcol=..., abdtop=..., abdblk=..., 
    abdbot=..., fbasis=..., y=..., yprime=..., ipivot=..., work=..., lw=1114, 
    icflag=0, ifgfdj=0, f=0x7fffd57a7630 <cb_f_in_bacoli__user__routines>, 
    fvec=0x7fffd57a7c80 <cb_fvec_in_bacoli__user__routines>, 
    bndxa=0x7fffd57a7080 <cb_bndxa_in_bacoli__user__routines>, 
    difbxa=0x7fffd57ad0b0 <bacoli_interface::dummy_difbx>, 
    bndxb=0x7fffd57a6ad0 <cb_bndxb_in_bacoli__user__routines>, 
    difbxb=0x7fffd57ad0b0 <bacoli_interface::dummy_difbx>, 
    vec=<error reading variable: Cannot access memory at address 0x8>)
    at bacoli_py/lib/bacoli.f:4048
4048	bacoli_py/lib/bacoli.f: No such file or directory.
```

**Comment by cbm755** [comment]
FWIW, it segaults on both Python 2.7.16 and Python 3.7.4.  My gcc and gfortran are 9.1.1.

**Comment by cbm755** [comment]
Six and Seven work fine on my Ubuntu 18.04 VM so maybe it is indeed Fedora  specific.

**Comment by cbm755** [comment]
### Fedora 30 (probably its a VM)

Six: works!
Seven: segfaults

**Comment by cbm755** [comment]
### Fedora Rawhide (probably its a VM)

(this is beta for Fedora 32)

No segfaults in 6 or 7!!  :-)

**Comment by cbm755** [comment]
### Fedora 30 Arm hardware

Six and Seven: no segfault!

Also: your software seems to work on some kind of arm (the sort with a hardware FP unit IIRC).

**Comment by cbm755** [comment]
My apologies, my machine is F30, not 31.

**Comment by cbm755** [comment]
Here's something a bit odd.  On Fedora **29**, ExampleSix works but Seven gives:
```
$ python3 ExampleSeven.py 
Traceback (most recent call last):
  File "ExampleSeven.py", line 113, in <module>
    f2py.compile(prob_def_f, modulename='problemdef', verbose=1)
  File "/usr/lib64/python3.7/site-packages/numpy/f2py/__init__.py", line 59, in compile
    f.write(source)
  File "/usr/lib64/python3.7/tempfile.py", line 481, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
```
This is odd b/c its the same Python version.  Its on a machine with python3-numpy-f2py-1.15.  Mine has python3-numpy-f2py-1.16.4.

If I change it to `f.encode('ascii')` then I get segfault on this machine to, just the same as https://github.com/connortannahill/bacoli_py/issues/2#issuecomment-523612717

**Comment by cbm755** [comment]
Some perhaps relevant data, here are the current versions of numpy-f2py on each Fedora version:

Rawhide | 1.17.0
Fedora 30 | 1.16.4
Fedora 29 | 1.15.1

**Comment by connortannahill** [comment]
I've run Examples Six and Seven on our Machine using Fedora 30. They ran successfully with no segfault.

I also attempted to try them with each of the different versions of numpy-f2py you listed in your most recent comment. They all worked with the exception of version 1.15.1, where I saw the same issue with the `TypeError: a bytes-like object is required, not 'str'` error message in Example Seven (Example Six worked fine). I used your `f.encode('ascii')` fix and it then worked with no segfault. I'll add this fix to ExampleSeven.

Something to attempt may be to update your numpy to the most recent version (1.17.0), re-install bacoli_py, and then attempt to run the example again.

**Comment by connortannahill** [comment]
Unfortunate!

The intent fix applies to both examples so it must be unrelated. Have you run it under gdb again? If so I would like to see the stack trace.
