### ISSUE TITLE
is dependeny on numpy missing?

### ISSUE THREAD

**Issue by cbm755** [connortannahill/bacoli_py#6]
On a very vanilla machine, I got:
```
$ pip3 install --user bacoli-py
Collecting bacoli-py
  Downloading https://files.pythonhosted.org/packages/3a/95/ebf1cadfca68f6b048e51bd36251edf44aa91e1e380b0fed0abf03efc021/bacoli_py-1.0.01.0.0.tar.gz (199kB)
    100% |████████████████████████████████| 204kB 4.0MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rgwhhk3m/bacoli-py/setup.py", line 3, in <module>
        from numpy.distutils.core import setup, Extension
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-rgwhhk3m/bacoli-py/
```

Maybe the numpy dependency is missing?

**Comment by cbm755** [comment]
`numpy-f2py` is needed too
